package com.inventles.data.pojo;

// Generated Dec 21, 2013 2:31:29 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BusinessEntity generated by hbm2java
 */
@Entity
@Table(name = "business_entity", catalog = "inventles")
public class BusinessEntity implements java.io.Serializable {

	private String entityCode;
	private String name;
	private Set<Item> items = new HashSet<Item>(0);
	private Set<Employee> employees = new HashSet<Employee>(0);
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<Customer> customers = new HashSet<Customer>(0);

	public BusinessEntity() {
	}

	public BusinessEntity(String entityCode) {
		this.entityCode = entityCode;
	}

	public BusinessEntity(String entityCode, String name, Set<Item> items,
			Set<Employee> employees, Set<Order> orders, Set<Customer> customers) {
		this.entityCode = entityCode;
		this.name = name;
		this.items = items;
		this.employees = employees;
		this.orders = orders;
		this.customers = customers;
	}

	@Id
	@Column(name = "entity_code", unique = true, nullable = false, length = 3)
	public String getEntityCode() {
		return this.entityCode;
	}

	public void setEntityCode(String entityCode) {
		this.entityCode = entityCode;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessEntity")
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessEntity")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessEntity")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessEntity")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
