package com.inventles.data.pojo;

// Generated Dec 21, 2013 2:31:29 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * BusinessEntity generated by hbm2java
 */
@Entity
@Table(name = "business_entity", catalog = "inventles")
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class BusinessEntity implements java.io.Serializable {

	private String entityCode;
	private String name;

	public BusinessEntity() {
	}

	public BusinessEntity(String entityCode) {
		this.entityCode = entityCode;
	}


	@Id
	@Column(name = "entity_code", unique = true, nullable = false, length = 3)
	public String getEntityCode() {
		return this.entityCode;
	}

	public void setEntityCode(String entityCode) {
		this.entityCode = entityCode;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
