package com.inventles.data.pojo;

// Generated Dec 21, 2013 2:31:29 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CodeList generated by hbm2java
 */
@Entity
@Table(name = "code_list", catalog = "inventles")
public class CodeList implements java.io.Serializable {

	private int codeListId;
	private CodeType codeType;
	private String codeListValue;
	private String codeListDesc;

	public CodeList() {
	}

	public CodeList(int codeListId, CodeType codeType, String codeListValue) {
		this.codeListId = codeListId;
		this.codeType = codeType;
		this.codeListValue = codeListValue;
	}

	public CodeList(int codeListId, CodeType codeType, String codeListValue,
			String codeListDesc) {
		this.codeListId = codeListId;
		this.codeType = codeType;
		this.codeListValue = codeListValue;
		this.codeListDesc = codeListDesc;
	}

	@Id
	@Column(name = "code_list_id", unique = true, nullable = false)
	public int getCodeListId() {
		return this.codeListId;
	}

	public void setCodeListId(int codeListId) {
		this.codeListId = codeListId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "code_type_id", nullable = false)
	public CodeType getCodeType() {
		return this.codeType;
	}

	public void setCodeType(CodeType codeType) {
		this.codeType = codeType;
	}

	@Column(name = "code_list_value", nullable = false, length = 45)
	public String getCodeListValue() {
		return this.codeListValue;
	}

	public void setCodeListValue(String codeListValue) {
		this.codeListValue = codeListValue;
	}

	@Column(name = "code_list_desc", length = 100)
	public String getCodeListDesc() {
		return this.codeListDesc;
	}

	public void setCodeListDesc(String codeListDesc) {
		this.codeListDesc = codeListDesc;
	}

}
