package com.inventles.data.pojo;

// Generated Dec 21, 2013 2:31:29 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CodeType generated by hbm2java
 */
@Entity
@Table(name = "code_type", catalog = "inventles")
public class CodeType implements java.io.Serializable {

	private int codeTypeId;
	private String codeTypeValue;
	private String codeTypeDesc;
	private Set<CodeList> codeLists = new HashSet<CodeList>(0);

	public CodeType() {
	}

	public CodeType(int codeTypeId, String codeTypeValue) {
		this.codeTypeId = codeTypeId;
		this.codeTypeValue = codeTypeValue;
	}

	public CodeType(int codeTypeId, String codeTypeValue, String codeTypeDesc,
			Set<CodeList> codeLists) {
		this.codeTypeId = codeTypeId;
		this.codeTypeValue = codeTypeValue;
		this.codeTypeDesc = codeTypeDesc;
		this.codeLists = codeLists;
	}

	@Id
	@Column(name = "code_type_id", unique = true, nullable = false)
	public int getCodeTypeId() {
		return this.codeTypeId;
	}

	public void setCodeTypeId(int codeTypeId) {
		this.codeTypeId = codeTypeId;
	}

	@Column(name = "code_type_value", nullable = false, length = 45)
	public String getCodeTypeValue() {
		return this.codeTypeValue;
	}

	public void setCodeTypeValue(String codeTypeValue) {
		this.codeTypeValue = codeTypeValue;
	}

	@Column(name = "code_type_desc", length = 100)
	public String getCodeTypeDesc() {
		return this.codeTypeDesc;
	}

	public void setCodeTypeDesc(String codeTypeDesc) {
		this.codeTypeDesc = codeTypeDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "codeType")
	public Set<CodeList> getCodeLists() {
		return this.codeLists;
	}

	public void setCodeLists(Set<CodeList> codeLists) {
		this.codeLists = codeLists;
	}

}
