package com.inventles.data.pojo;

// Generated Dec 21, 2013 2:31:29 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerOrder generated by hbm2java
 */
@Entity
@Table(name = "customer_order", catalog = "inventles")
public class CustomerOrder implements java.io.Serializable {

	private int customerOrderId;
	private Customer customer;
	private Order order;

	public CustomerOrder() {
	}

	public CustomerOrder(int customerOrderId, Customer customer, Order order) {
		this.customerOrderId = customerOrderId;
		this.customer = customer;
		this.order = order;
	}

	@Id
	@Column(name = "customer_order_id", unique = true, nullable = false)
	public int getCustomerOrderId() {
		return this.customerOrderId;
	}

	public void setCustomerOrderId(int customerOrderId) {
		this.customerOrderId = customerOrderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

}
