package com.inventles.data.pojo;

// Generated Dec 21, 2013 2:31:29 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeOrder generated by hbm2java
 */
@Entity
@Table(name = "employee_order", catalog = "inventles")
public class EmployeeOrder implements java.io.Serializable {

	private int employeeOrderId;
	private Employee employee;
	private Order order;

	public EmployeeOrder() {
	}

	public EmployeeOrder(int employeeOrderId, Employee employee, Order order) {
		this.employeeOrderId = employeeOrderId;
		this.employee = employee;
		this.order = order;
	}

	@Id
	@Column(name = "employee_order_id", unique = true, nullable = false)
	public int getEmployeeOrderId() {
		return this.employeeOrderId;
	}

	public void setEmployeeOrderId(int employeeOrderId) {
		this.employeeOrderId = employeeOrderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

}
